name: lowkey
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "1.7.0"
  firebase_storage: "^10.0.5"
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  google_fonts: ^2.1.0
  overlay_support: ^1.2.1
  email_validator: ^2.0.1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets: 
    - lib/UI/assets/highland.png
    - lib/UI/assets/reg.jpeg
    - lib/UI/assets/rev.jpg
    - lib/UI/assets/logo.png
    - lib/UI/assets/coffee.png
    - lib/UI/assets/fizz.png
    - lib/UI/assets/pizza.png
    - lib/UI/assets/starbucks.jpg

  fonts:
    - family: MyFlutterApp
      fonts:
      - asset: lib/UI/assets/fonts/MyFlutterApp.ttf
